### ISSUE TITLE
Use other element than a button..

### ISSUE THREAD

**Issue by sagive** [oncode/handorgel#7]
i needed to place these accordion inside a form and the fact 
that i cant choose the trigger element by type / class is a problem.

Anyway around that?

**Comment by oncode** [comment]
Hi @sagive 
Sorry for the late response, had holidays.

Is the problem that the form gets submitted when you click a button? You can add `role="button"` to the button elements to prevent them from submitting the form. Alternatively, you should be able to use any other instead of the button, but I wouldn't recommend it in terms of accessibility. Hope this helps?

**Comment by sagive** [comment]
Thanks - going to try that ;)
